module.exports = {
    CAPTURE_START: Symbol('CAPTURE_START'),
    CAPTURE_END: Symbol('CAPTURE_END'),
    TOKEN_CAPTURE_START: Symbol('TOKEN_CAPTURE_START'),
    TOKEN_CAPTURE_END: Symbol('TOKEN_CAPTURE_END'),
    CAPTURED: Symbol('CAPTURED_ARG'),
    COMMENT_CLOSE: Symbol('COMMENT_CLOSE_ARG'),
}